// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgojfznjgcqqqsbttoyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnb2pmem5qZ2NxcXFzYnR0b3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjYwOTgsImV4cCI6MjA2NjE0MjA5OH0.vAsd-VKvgNTe41v-vekexiSLIrY2TBUDS0DV7nANFz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);